steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/documentai-commonforms-worker', '-f', 'Dockerfile.worker', '.']
images:
  - 'gcr.io/$PROJECT_ID/documentai-commonforms-worker'
