# Cloud Build configuration for CommonForms Worker
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/commonforms-worker:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/commonforms-worker:latest'
      - '-f'
      - 'workers/cf/Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/commonforms-worker:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/commonforms-worker:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'commonforms-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/commonforms-worker:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '300'
      - '--no-allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/commonforms-worker:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/commonforms-worker:latest'

timeout: '1200s'
