# Cloud Build configuration for Vision Worker

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/documentai-vision-worker:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/documentai-vision-worker:latest'
      - '-f'
      - 'workers/vision/Dockerfile'
      - '.'
    dir: '../..'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/documentai-vision-worker:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/documentai-vision-worker:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'documentai-vision-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/documentai-vision-worker:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'

images:
  - 'gcr.io/$PROJECT_ID/documentai-vision-worker:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/documentai-vision-worker:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
